name: WebdriverIO Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  webdriverio_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Custom Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: wdio-runner:latest

      - name: Run WDIO Tests (using CMD from Dockerfile)
        run: |
          mkdir -p allure-results

          docker run --rm \
            -v ${{ github.workspace }}/allure-results:/usr/src/app/allure-results \
            wdio-runner:latest

      - name: Generate & Publish Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allure_results_path: allure-results
          allure_report_path: allure-report
          issue_pr: true

      - name: Upload Allure HTML
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 10
